openapi: 3.0.1
info:
  title: Hi
  description: Your API Description
  version: '1.0.0'
servers:
  - url: http://localhost:5000

paths:
  /hello:
    get:
      summary: Get a greeting
      responses:
        '200':
          description: OK
          schema:
            type: string
